### ISSUE TITLE
Crashing with Twilight Forest

### ISSUE THREAD

**Issue by Null-151** [joshuaepstein/advancementtrophies#4]
Just as the title says, seems to crash anytime you unlock a Twilight Forest advancement
Forge Version: 40.1.68 / Twilight Forest Version: 4.1.1220 / Advancement Trophies Version: 1.1

Also sorry for the wall of text lol I dunno how to do a dropdown here

at java.base/java.lang.Thread.run(Thread.java:833)

[02:21:52] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.DisplayInfo.m_14992_()" because the return value of "net.minecraft.advancements.Advancement.m_138320_()" is null
	at joshuaepstein.advancementtrophies.event.AdvancementEvents.onGain(AdvancementEvents.java:32) ~[advancementtrophies-1.1.jar%2354!/:1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_12_AdvancementEvents_onGain_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1018) ~[forge-1.18.2-40.1.68-universal.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen.mixins.json:ForgeHooksMixin,pl:mixin:APP:pollen.mixins.json:loot.ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:260) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.LocationTrigger.m_53645_(LocationTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:pollen-common.mixins.json:ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	... 6 more
[02:21:52] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 201364bd-f4d5-43e7-870e-a1434f768603
[02:21:52] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: F:\PolyMC\instances\1.18.21\.minecraft\crash-reports\crash-2022-07-31_02.21.52-server.txt
[02:21:52] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[02:21:52] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[02:21:52] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID e243c2c5-1b62-48b8-a706-734204e06d1f
---- Minecraft Crash Report ----
// You're mean.

Time: 7/31/22, 2:21 AM
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.DisplayInfo.m_14992_()" because the return value of "net.minecraft.advancements.Advancement.m_138320_()" is null
	at joshuaepstein.advancementtrophies.event.AdvancementEvents.onGain(AdvancementEvents.java:32) ~[advancementtrophies-1.1.jar%2354!/:1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_12_AdvancementEvents_onGain_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1018) ~[forge-1.18.2-40.1.68-universal.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen.mixins.json:ForgeHooksMixin,pl:mixin:APP:pollen.mixins.json:loot.ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:260) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.LocationTrigger.m_53645_(LocationTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:pollen-common.mixins.json:ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at joshuaepstein.advancementtrophies.event.AdvancementEvents.onGain(AdvancementEvents.java:32) ~[advancementtrophies-1.1.jar%2354!/:1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_12_AdvancementEvents_onGain_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1018) ~[forge-1.18.2-40.1.68-universal.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen.mixins.json:ForgeHooksMixin,pl:mixin:APP:pollen.mixins.json:loot.ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:260) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.LocationTrigger.m_53645_(LocationTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 261
	Entity Name: O_bot
	Entity's Exact location: 24.01, 17.69, 230.07
	Entity's Block location: World: (24,17,230), Section: (at 8,1,6 in 1,1,14; chunk contains blocks 16,-32,224 to 31,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-32,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:pollen-common.mixins.json:ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by joshuaepstein** [comment]
You are running an older version of the mod, what version of minecraft are you using

**Comment by Null-151** [comment]
Sorry forgot to say, I'm on 1.18.2

**Comment by joshuaepstein** [comment]
I will try to fix the 1.18 version. I was aware of an issue with this. Should be out either tonight or tomorrow

**Comment by joshuaepstein** [comment]
Hi @Null-151 I have uploaded a fix to advancement trophies, It is also on modrinth as curse hasn't accepted it, you can find it here: https://modrinth.com/mod/advancement-trophies

**Comment by joshuaepstein** [comment]
Let me know if this fixes your issue
